### ISSUE TITLE
Response code: 529 - Error on requesting API. Waiting 30 sec until next retry

### ISSUE THREAD

**Issue by ChennaiTechie** [kyhau/ssllabs-scan#50] opened 2020-12-15 08:20 UTC
Website scan is struck with above error. 

Environment: Ubuntu

**Comment by kyhau** [comment] 2020-12-15 09:38
529 means "the service is overloaded".

The SSL Labs Assessment API has access rate limits.

You can find more details in the section "Error Response Status Codes" and "Access Rate and Rate Limiting" in the official docs https://github.com/ssllabs/ssllabs-scan/blob/stable/ssllabs-api-docs.md

**Comment by ChennaiTechie** [comment] 2020-12-15 12:21
Thanks @kyhau , Is it possible to add status of RC4 ?

![image](https://user-images.githubusercontent.com/46935896/102214297-7b345600-3ef1-11eb-871c-b2ce9243aa66.png)

**Comment by kyhau** [comment] 2020-12-15 20:24
Will see if have time to add RC4 in the next few days.

Closing this ticket as 529 is not a bug.

**Closed by kyhau** 2020-12-15 20:24 UTC

**Comment by kyhau** [comment] 2020-12-16 10:00
@ChennaiTechie see https://github.com/kyhau/ssllabs-scan/pull/52 for the "RC4" CR
